### ISSUE TITLE
warnings

### ISSUE THREAD

**Issue by Polygons1** [Snowiiii/Pumpkin#231]
### I've searched existing issues and couldn't find a duplicate.

- [X] I confirm this is not a duplicate.

### Operating System

macOS Sonoma

### Server Software Version/Commit

87aa5ec

### What happened?

a lot of `[pumpkin::entity::player@tokio-runtime-worker] Failed to handle player packet id 0x0b` warnings and one with `0x08` instead of `0x0b` at the start

### To Reproduce

start the server and join, nothing changed

### Expected behavior

the world to work, currently I am seeing unbreakable stone blocks in front of me

**Comment by Polygons1** [comment]
and what is 0x08?

**Comment by Snowiiii** [comment]
So the the Problem was that i moved to a different Serverbound Packet reading solution in https://github.com/Snowiiii/Pumpkin/commit/1842e8e6b19f05b5a360cde95593cb8b9f1cbcf0. So it would log when receiving Packets we don't implemented. 
Looking at wiki.vg 0x0b and 0x08 are completely different. I found at that these Packet IDs correspond to `ClientTickEnd` and `PlayerInput` by looking at our packets.json from our own extractor. Also wiki.vg has wrong implementation of the PlayerInput packet. Im tbh really disappointed with wiki.vg and will avoid using it for Packet Reference in the future.

Using the latest commit the issue should be fixed

**Comment by Polygons1** [comment]
now there is a `Failed to handle player packet id 8` warning

**Comment by Snowiiii** [comment]
> 8

Yeah i say that, That should be `chat_session_update`. But that is nothing Wild. It only gets send when the client joins. It ways less annoying than the other Packets which get send all the time and give us warns.
