### ISSUE TITLE
Missing field 'signatureRequired' when using drasl auth server

### ISSUE THREAD

**Issue by StefanB7** [Snowiiii/Pumpkin#301]
### I've searched existing issues and couldn't find a duplicate.

- [X] I confirm this is not a duplicate.

### Operating System

Ubuntu 24.04

### Server Software Version/Commit

0.1.0/00af2b98683b11946cddb4f08de3b0ce04c1fddd

### What happened?

I've set up an drash auth server and changed the `auth_url` in `features.toml` to point to the auth server.
When I try to join the server, I get an error: 
```
[pumpkin::client@tokio-runtime-worker] Kicking Client id 0 for Texture Error Failed to parse JSON from player texture: missing field `signatureRequired` at line 1 column 279
```

The response returned by my auth server at `https://<hostname>/session/minecraft/hasJoined?username={username}&serverId={server_hash}` looks like this:
```
{
    "id": "<an-id>",
    "name": "stefan",
    "properties": [
        {
            "name": "textures",
            "value": "<value>",
            "signature": <signature>"
        }
    ]
}
```

there is indeed no `signatureRequired` property. I removed the `signature_required` property from the `ProfileTextures` struct in `src/client/authentication.rs` and I could join the world.

### To Reproduce

- Set up drasl auth server
- Create account
- Change `auth_url` in `features.toml`
- Run server
- Try to join server from client authenticated through drasl

### Expected behavior

The server should let you join

**Comment by Snowiiii** [comment]
Weird. I wonder how `properties.value` looks like. It is an base64 utf8 string

**Comment by StefanB7** [comment]
> Weird. I wonder how `properties.value` looks like. It is an base64 utf8 string

Yes it is

**Comment by Snowiiii** [comment]
> > Weird. I wonder how `properties.value` looks like. It is an base64 utf8 string
> 
> Yes it is

How does it look like?. Normal Minecraft auth hss the signatureRequired boolean

**Comment by Snowiiii** [comment]
Further information is required to proceed.

**Comment by exalented** [comment]
> Weird. I wonder how `properties.value` looks like. It is an base64 utf8 string

This occurs independent of if the skin/cape is set.
No skin set
`{"timestamp":1234123412341234123,"profileId":"69133769133769691337694206942069","profileName":"Rizz_Wars","textures":{}}`

With Skin set
```
{"timestamp":1234123412341234123,"profileId":"69133769133769691337694206942069","profileName":"Rizz_Wars","textures":{"SKIN":{"url":"https://domain.tld/web/texture/skin/<__________some letters and numbers that equal this length____________>.png","metadata":{"model":"classic"}},"CAPE":{"url":"https://domain.tld/web/texture/cape/<__________some letters and numbers that equal this length____________> .png"}}}
```

**Comment by rrtt217** [comment]
To add further information:
As for standard:
- Authlib-injector doc: no reference of `signatureRequired`. See https://yushijinhun.github.io/authlib-injector/en/yggdrasil-server-technical-specification.html#serialization-of-profile-information
- Minecraft Wiki: unclear. https://minecraft.wiki/w/Java_Edition_protocol/Encryption has no reference of `signatureRequired`; https://minecraft.wiki/w/Mojang_API#:~:text=Verify%20login%20session%20on%20server do not mention whether `signatureRequired` may be present; it is present with `https://sessionserver.mojang.com/session/minecraft/profile/<UUID>?unsigned=false` but not applicable for `hasJoined` endpoint.

As for implementation:
- Pumpkin itself: `signatureRequired` is never used except its definition: https://github.com/Pumpkin-MC/Pumpkin/blob/master/pumpkin/src/net/authentication.rs#L22
- Auth Server Implementstions: 
    - Drasl: no reference of `signatureRequired`. See https://github.com/search?q=repo%3Aunmojang%2Fdrasl%20signatureRequired&type=code;
    - Microsoft itself: seems to always use `signatureRequired` so it works fine for microsoft auth;
    - Blessing Skin: same as drasl.

Also it seems that https://docs.pumpkinmc.org/config/introduction is really outdated.
- `features.toml` no longer present;
- https://docs.pumpkinmc.org/config/authentication#auth-url-string-optional this config entry is indeed `url` instead of `auth_url` in current pumpkin.

I found the exact same issue when I finally figured out the right config entry by directly looking up source code on Github.
It seems that common thirdparty auth server do not contains `signatureRequired` in their response.

**Comment by rrtt217** [comment]
Test result:
- Drasl (Using https://drasl.unmojang.org/): missing field `signatureRequired` at line 1 column xxx
- Blessing skin (Using littleskin.cn): missing field `signatureRequired` at line 1 column xxx
- (https://github.com/water2004/element-skin): missing field `signatureRequired` at line 1 column xxx
Tested on latest nightly.
