### ISSUE TITLE
Unable to compile in Termux since `sys-info` lib was added

### ISSUE THREAD

**Issue by BlueGradientHorizon** [Snowiiii/Pumpkin#311]
### I've searched existing issues and couldn't find a duplicate.

- [X] I confirm this is not a duplicate.

### Operating System

Termux 0.119.0-beta1, Android 14

### Server Software Version/Commit

a23ce773ad170a6507e79c4aab43693783ec58ae

### What happened?

Since [that exact commit](https://github.com/Snowiiii/Pumpkin/commit/e4190459edad91f0f5e82c05520d7f0871f555b2) it became impossible to build Pumpkin. It is a [known issue](https://github.com/FillZpp/sys-info-rs/issues/116) and I'm getting the exact same error message.

### To Reproduce

Download and install Termux from F-Droid, update packages, install cargo and git, clone repo and try `cargo build`.

### Expected behavior

To be able to compile and run Pumpkin in Termux without issues.

**Comment by Commandcracker** [comment]
Was about to say let's see if they merge this: https://github.com/FillZpp/sys-info-rs/pull/118, but it looks like they stopped working on sys-info 2 years ago.

Is it possible to make creates optional ? This would be nice because it is not mandatory.

I also found heim witch is async and fully written in rust, but development is also inactive.

They also list some other options see https://github.com/heim-rs/heim/blob/master/COMPARISON.md

**I think we should definitely switch from "sys-info" to "sysinfo", it's fully written in rust and is actively developed.** (I'll make a PR soon)
